# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='value',
            new_name='latitude_val',
        ),
        migrations.AddField(
            model_name='map',
            name='longitude_val',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
