# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170122_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
