# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_map_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='date',
        ),
    ]
