# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20170123_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='maps',
            field=models.ManyToManyField(to='main_app.Map'),
        ),
    ]
