# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_person_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='maps',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='latitude_val',
            new_name='center_latitude_val',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='longitude_val',
            new_name='center_longitude_val',
        ),
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
